[package]
name = "message"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34", features = ["full"] }
snow = "0.6.2"
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.4"
dirs = "4.0"
base64 = "0.21"
rand = "0.8"